/** CONECTAR COM A BASE FILIAIS DESEJADA*/
SELECT DATAOPERACAOCHECKOUT, NUMEROVOOPAX,
SUM(NVL(precounitariovenda,0)* NVL(quantidadevendida,0)) as VENDAS,
COUNT(DISTINCT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT)) AS TRANS,
SUM(NVL(quantidadevendida,0)) AS QTD
from (SELECT   C.CODIGOLOJA,
C.DATAOPERACAOCHECKOUT, to_char(C.DATAOPERACAOCHECKOUT, 'YYYY-MM') AS ANO_MES,
a.NUMEROCHECKOUT, a.SEQUENCIALOPERACAOCHECKOUT,
a.NUMERONOTAVENDA, a.CODIGOBRASIF, C.NUMEROVOOPAX, 
a.PRECOUNITARIOVENDA, a.QUANTIDADEVENDIDA, 
b.CODIGOGRUPO, b.CODIGOSUBGRUPO, b.CODIGOCATEGORIADUFRY,
b.DESCRICAOITEM,  b.IDENTIFICACAOMARCA
from itvet001@brd05 a, itemt027@brd05 b, CHCKT002@brd05 C, VNDAT004@brd05 D, paist001 e
where  C.dataoperacaocheckout between to_date('01/01/2017', 'dd/mm/yyyy') and to_date('31/01/2017', 'dd/mm/yyyy') 
and b.codigobrasif(+)=a.codigobrasif 
and c.CODIGOPAISPAX=e.CODIGOPAISPDV(+)
AND b.codigonegocio = '200' 
and substr(c.NUMEROVOOPAX,1,2) = 'JJ'
and a.NUMEROCHECKOUT = D.NUMEROCHECKOUT
and a.SEQUENCIALOPERACAOCHECKOUT = D.SEQUENCIALOPERACAOCHECKOUT
and a.NUMEROCHECKOUT = C.NUMEROCHECKOUT
and a.SEQUENCIALOPERACAOCHECKOUT = C.SEQUENCIALOPERACAOCHECKOUT
and NVL(d.INDICADORESTORNO,'N') = 'N')
GROUP BY DATAOPERACAOCHECKOUT, NUMEROVOOPAX




select * from CHCKT002@brd05
