/*CASE COM GROUP BY */

/*TESTAR*/
SELECT 
NUMEROCHECKOUT, SEQUENCIALOPERACAOCHECKOUT,
SUM(VALORNOTAVENDABRUTO) AS VALOR_NOTA
FROM BASE_C
group by NUMEROCHECKOUT, SEQUENCIALOPERACAOCHECKOUT
,     CASE WHEN VALOR_NOTA>100 THEN 'A' WHEN VALO_NOTA<=100 THEN 'B' ELSE 'Z' END AS FAIXA

select * from itvet001

select 
CODIGOBRASIF,
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
RANK() OVER (PARTITION BY NUMEROCHECKOUT, SEQUENCIALOPERACAOCHECKOUT ORDER BY CODIGOBRASIF ) as CONT_REP
FROM ITVET001
WHERE DATAOPERACAOCHECKOUT BETWEEN '01-JUN-2009' AND '01-JUN-2009'


/*CRIANDO CONTADORES DE TRANSAÇÃO, CLIENTES, ETC*/
CREATE TABLE TESTE_FLA AS SELECT
TIPODOCUMENTOPAX,
NUMERODOCUMENTOPAX,
DATAOPERACAOCHECKOUT,
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
(DATAOPERACAOCHECKOUT - (LAG( DATAOPERACAOCHECKOUT,1 ) OVER ( PARTITION BY TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX ORDER BY DATAOPERACAOCHECKOUT))) AS DATADIF,
RANK() OVER (PARTITION BY TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX ORDER BY DATAOPERACAOCHECKOUT ) as CONT_REP
FROM VNDAV004
WHERE DATAOPERACAOCHECKOUT BETWEEN '23-AGO-2007' AND '30-AGO-2007'

/*1 - SELECT TOP*/

/*sql server*/
SELECT TOP 10 product, descr, email 
FROM products 
order by product

/*oracle*/
SELECT product, descr, email
FROM products 
WHERE ROWNUM <= 10

/*my sql*/
SELECT product, descr, email
FROM products
LIMIT 10


/*2 - VENDA LÍQUIDA*/
SELECT DATAOPERACAOCHECKOUT,
sum(nvl(valornotavendabruto,0)) GROSS_AMOUNT,
sum(nvl(valornotavendabruto,0))- sum(nvl(valortotaldescontoestado,0))-sum(nvl(valortotaldescontoetiqueta,0))
- sum(nvl(valortotaldescontopreorder,0))- sum(nvl(valortotaldescontotripulante,0)) - sum(nvl(VALORDESCONTONOTA,0)) AS NET_AMOUNT
FROM VNDAV004
WHERE DATAOPERACAOCHECKOUT BETWEEN '01-JAN-2007' AND '31-JAN-2007'
AND NVL(INDICADORESTORNO,'N')='N'
AND CODIGONEGOCIO='200'
GROUP BY DATAOPERACAOCHECKOUT



/*3 - SYSDATE*/
/*EXEMPLO*/
SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, 
DATAOPERACAOCHECKOUT
FROM VNDAV004
WHERE DATAOPERACAOCHECKOUT BETWEEN 
TRUNC ( ADD_MONTHS ( SYSDATE , - 2 ), 'month' ) 
AND TRUNC ( SYSDATE ) - 1 / 86400 

/*SYSDATE É A DATA ATUAL*/
SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, 
DATAOPERACAOCHECKOUT,
(SYSDATE - 2) AS DATA
FROM VNDAV004

SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, 
DATAOPERACAOCHECKOUT,
ADD_MONTHS(SYSDATE , - 5) AS DATA
FROM VNDAV004

SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, 
DATAOPERACAOCHECKOUT,
(DATAOPERACAOCHECKOUT - (TRUNC(ADD_MONTHS(SYSDATE, -5))) )/30 AS MESES
FROM VNDAV004
WHERE DATAOPERACAOCHECKOUT BETWEEN '01-APR-07' AND '30-MAY-07'








/*PARTITION OVER*/
select
sum(valornotavendabruto) partition over 

/*SOMA ACUMULADA*/
select tipodocumentopax, numerodocumentopax, dataoperacaocheckout, (sum(cont)over (partition by (tipodocumentopax||numerodocumentopax) order by dataoperacaocheckout)) as seq
from 
(select tipodocumentopax, numerodocumentopax, dataoperacaocheckout,
case
when dataoperacaocheckout is not null then '1'
else '0'
end as cont
from vndav004 where dataoperacaocheckout between '14-jun-2007' and '15-jun-2007'
and codigoloja in ('21'))

/*pivot tables - não testei*/
Select ano
, [1] as Jan
, [2] as Fev
, [3] as Mar
, [4] as Abr 
from venda pivot (sum(valor) for mes in ([1],[2],[3],[4])) p 
order by 1;
