/*1 - JOIN DA BASE DE PAGAMENTO COM A DE VENDAS*/

/*A - BASE 1 - VENDA*/
CREATE TABLE VVV AS SELECT 
DATAOPERACAOCHECKOUT,
CODIGOLOJA,
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
NUMERONOTAVENDA,
(TIPODOCUMENTOPAX||'|'||NUMERODOCUMENTOPAX) AS DOC,
VALORNOTAVENDABRUTO AS VALORNOTAVENDABRUTO,
NVL(valornotavendabruto,0)- NVL(valortotaldescontoestado,0)- NVL(valortotaldescontoetiqueta,0)
- NVL(valortotaldescontopreorder,0)- NVL(valortotaldescontotripulante,0) - NVL(VALORDESCONTONOTA,0)
AS VALORNOTAVENDALIQUIDO
FROM VNDAT004
WHERE NVL(INDICADORESTORNO, 'N')='N'
AND DATAOPERACAOCHECKOUT BETWEEN '13-ago-2007' AND '14-ago-2007'

/*B - BASE 2 - PGTO*/
CREATE TABLE PPP AS SELECT
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
SUM(VALORPAGAMENTOUS$) AS VALORPAGAMENTOUS$,
SUM(VENDA_LIQUIDA_PGTO) AS VENDA_LIQUIDA_PGTO,
MAX(FLAG_PARC3X) AS FLAG_PARC3X,
MAX(FLAG_PARC5X) AS FLAG_PARC5X
FROM
(SELECT
DATAOPERACAOCHECKOUT,
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
CODIGOLOJA,
VALORPAGAMENTOUS$,
(VALORPAGAMENTOUS$ - VALORTROCOMOEDABASE) AS VENDA_LIQUIDA_PGTO,
CASE
WHEN NUMEROPARCELASCARTAO IN ('2','3') THEN '1'
END AS FLAG_PARC3X,
CASE
WHEN NUMEROPARCELASCARTAO IN ('4','5') THEN '1'
END AS FLAG_PARC5X
FROM PGTOV001
WHERE NVL(INDICADORESTORNO, 'N')='N'
AND DATAOPERACAOCHECKOUT BETWEEN '13-ago-2007' AND '14-ago-2007'
) GROUP BY NUMEROCHECKOUT, SEQUENCIALOPERACAOCHECKOUT


/*C - BASE 3 - JOIN*/
CREATE TABLE JOIN_C_D AS SELECT 
V.DATAOPERACAOCHECKOUT,
V.CODIGOLOJA,
V.DOC,
V.NUMEROCHECKOUT,
V.SEQUENCIALOPERACAOCHECKOUT,
V.VALORNOTAVENDABRUTO,
V.VALORNOTAVENDALIQUIDO,
P.VALORPAGAMENTOUS$,
P.VENDA_LIQUIDA_PGTO,
P.FLAG_PARC3X,
P.FLAG_PARC5X
FROM VVV V, PPP P
WHERE V.NUMEROCHECKOUT=P.NUMEROCHECKOUT AND V.SEQUENCIALOPERACAOCHECKOUT=P.SEQUENCIALOPERACAOCHECKOUT


/*2 - JOIN DA BASE DE PAGAMENTO COM A DE ITENS COM A DESCRIÇÃO DOS ITENS*/

/*A - BASE DE ITENS COM FLAG E VALOR DE GRUPOS*/
CREATE TABLE III AS SELECT 
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
DECODE(CODIGOGRUPO, '01', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_BEBIDAS,
DECODE(CODIGOGRUPO, '02', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_FUMOS,
DECODE(CODIGOGRUPO, '03', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_COMESTIVEIS,
DECODE(CODIGOGRUPO, '04', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_PERFUMES,
DECODE(CODIGOGRUPO, '05', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_COSMETICOS,
DECODE(CODIGOGRUPO, '06', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_PRESENTES,
DECODE(CODIGOGRUPO, '07', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_ELETRONICOS,
DECODE(CODIGOGRUPO, '08', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_ESPORTELAZER,
DECODE(CODIGOGRUPO, '09', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_GAP,
DECODE(CODIGOGRUPO, '01', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_BEBIDAS,
DECODE(CODIGOGRUPO, '02', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_FUMOS,
DECODE(CODIGOGRUPO, '03', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_COMESTIVEIS,
DECODE(CODIGOGRUPO, '04', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_PERFUMES,
DECODE(CODIGOGRUPO, '05', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_COSMETICOS,
DECODE(CODIGOGRUPO, '06', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_PRESENTES,
DECODE(CODIGOGRUPO, '07', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_ELETRONICOS,
DECODE(CODIGOGRUPO, '08', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_ESPORTELAZER,
DECODE(CODIGOGRUPO, '09', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QUANTIDADE_GAP,
DECODE(IDENTIFICACAOMARCA, 'V.SECRET', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_VS,
DECODE(IDENTIFICACAOMARCA, 'MAC', (NVL(PRECOUNITARIOVENDA,0)*NVL(QUANTIDADEVENDIDA,0)) , NULL) AS VALOR_MAC,
DECODE(IDENTIFICACAOMARCA, 'V.SECRET', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QTD_VS,
DECODE(IDENTIFICACAOMARCA, 'MAC', (NVL(QUANTIDADEVENDIDA,0)) , NULL) AS QTD_MAC
FROM
(SELECT 
a.SIGLAAEROPORTO,  
a.CODIGOLOJA,
a.TIPOLOJA,
a.DATAOPERACAOCHECKOUT, 
a.INDICADORESTORNO, 
a.NUMEROCHECKOUT, 
a.SEQUENCIALOPERACAOCHECKOUT, 
a.CODIGOBRASIF,
a.PRECOUNITARIOVENDA, a.QUANTIDADEVENDIDA, 
b.CODIGOGRUPO, b.CODIGOSUBGRUPO, 
b.DESCRICAOITEM,  b.IDENTIFICACAOMARCA
from itvev001 a, itemt027 b
where  a.dataoperacaocheckout between '11-AGO-2007' and '12-AGO-2007'
and a.codigonegocio = '200'
and (b.codigobrasif(+)=a.codigobrasif and a.codigonegocio = b.codigonegocio)
and nvl(a.indicadorestorno, 'N')='N')


/*B - BASE DE ITENS AGG POR NOTA*/

CREATE TABLE III_AGG AS SELECT 
NUMEROCHECKOUT,
SEQUENCIALOPERACAOCHECKOUT,
SUM(VALOR_BEBIDAS)  AS VALOR_BEBIDAS,
SUM(VALOR_FUMOS) AS VALOR_FUMOS,
SUM(VALOR_COMESTIVEIS) AS VALOR_COMESTIVEIS,
SUM(VALOR_PERFUMES) AS VALOR_PERFUMES,
SUM(VALOR_COSMETICOS) AS VALOR_COSMETICOS,
SUM(VALOR_PRESENTES) AS VALOR_PRESENTES,
SUM(VALOR_ELETRONICOS) AS VALOR_ELETRONICOS,
SUM(VALOR_ESPORTELAZER) AS VALOR_ESPORTELAZER,
SUM(VALOR_GAP) AS VALOR_GAP,
SUM(QUANTIDADE_BEBIDAS) AS QUANTIDADE_BEBIDAS,
SUM(QUANTIDADE_FUMOS) AS QUANTIDADE_FUMOS,
SUM(QUANTIDADE_COMESTIVEIS) AS QUANTIDADE_COMESTIVEIS,
SUM(QUANTIDADE_PERFUMES) AS QUANTIDADE_PERFUMES,
SUM(QUANTIDADE_COSMETICOS) AS QUANTIDADE_COSMETICOS,
SUM(QUANTIDADE_PRESENTES) AS QUANTIDADE_PRESENTES,
SUM(QUANTIDADE_ELETRONICOS) AS QUANTIDADE_ELETRONICOS,
SUM(QUANTIDADE_ESPORTELAZER) AS QUANTIDADE_ESPORTELAZER,
SUM(QUANTIDADE_GAP) AS QUANTIDADE_GAP,
SUM(VALOR_VS) AS VALOR_VS,
SUM(VALOR_MAC) AS VALOR_MAC,
SUM(QTD_VS) AS QTD_VS,
SUM(QTD_MAC) AS QTD_MAC
FROM III
GROUP BY NUMEROCHECKOUT, SEQUENCIALOPERACAOCHECKOUT
