SELECT ANO_MES, SIGLAAEROPORTO, TIPOLOJA, NACIONALIDADE,
SUM(NVL(precounitariovenda,0)* NVL(quantidadevendida,0)) as VENDAS,
COUNT(DISTINCT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT)) AS TRANS,
SUM(NVL(quantidadevendida,0)) AS QTD
from (SELECT a.SIGLAAEROPORTO,   a.CODIGOLOJA,
CASE
WHEN CODIGOPAISPAX IN ('1','01') THEN 'BRASILEIROS'
ELSE 'ESTRANGEIROS' END AS NACIONALIDADE,
a.TIPOLOJA, a.DATAOPERACAOCHECKOUT, to_char(a.DATAOPERACAOCHECKOUT, 'YYYY-MM') AS ANO_MES,
a.NUMEROCHECKOUT, a.SEQUENCIALOPERACAOCHECKOUT,
a.NUMERONOTAVENDA, a.CODIGOBRASIF,
a.PRECOUNITARIOVENDA, a.QUANTIDADEVENDIDA, 
b.CODIGOGRUPO, b.CODIGOSUBGRUPO, b.CODIGOCATEGORIADUFRY,
b.DESCRICAOITEM,  b.IDENTIFICACAOMARCA
from itvet001 a, itemt027 b
where  a.dataoperacaocheckout between to_date('01/01/2013', 'dd/mm/yyyy') and to_date('31/08/2013', 'dd/mm/yyyy') 
and a.codigonegocio = '200'
and (b.codigobrasif(+)=a.codigobrasif and a.codigonegocio = b.codigonegocio(+))
and nvl(A.indicadorestorno, 'N')='N')
GROUP BY ANO_MES, SIGLAAEROPORTO, TIPOLOJA, NACIONALIDADE
