
CREATE TABLE FL_ESTUDO_NACIONALIDADE AS SELECT ANO_MES, NOMEPAIS, TIPOLOJA, 
SUM(NVL(precounitariovenda,0)* NVL(quantidadevendida,0)) AS VENDAS,
COUNT(DISTINCT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT||NUMERONOTAVENDA)) AS TRANS,
SUM(NVL(quantidadevendida,0)) AS QTD
FROM 
(SELECT a.SIGLAAEROPORTO, a.TIPOLOJA, a.CODIGOLOJA, a.DATAOPERACAOCHECKOUT,
TO_CHAR(a.DATAOPERACAOCHECKOUT, 'YYYY-MM') AS ANO_MES,
C.NOMEPAIS,
a.NUMEROCHECKOUT, a.SEQUENCIALOPERACAOCHECKOUT,
a.NUMERONOTAVENDA, a.PRECOUNITARIOVENDA, a.QUANTIDADEVENDIDA, 
B.CODIGOCATEGORIADUFRY
from itvet001 a, itemt027 b, PAIST001 C
where  a.dataoperacaocheckout between '01-JAN-2015' and '31-dec-2015'
and a.codigonegocio = '200' 
AND a.CODIGOPAISPAX = C.CODIGOPAISPDV(+)
and (b.codigobrasif(+)=a.codigobrasif and a.codigonegocio = b.codigonegocio(+))
and nvl(a.indicadorestorno, 'N')='N')
group by ANO_MES, NOMEPAIS, TIPOLOJA
