DROP TABLE FL_VENDA_SUB_TIPO

CREATE TABLE FL_VENDA_SUB_TIPO AS SELECT ANO_MES, CODIGOCATEGORIADUFRY, 
CODIGOGRUPO, DESCRICAOSUBGRUPO, CODIGOTIPO,DESCRICAOTIPO,
SUM(PRECOUNITARIOVENDA * QUANTIDADEVENDIDA) AS VENDAS
FROM (SELECT
a.TIPODOCUMENTOPAX,
a.NUMERODOCUMENTOPAX,
a.SIGLAAEROPORTO,
a.CODIGOLOJA,
a.TIPOLOJA,
a.DATAOPERACAOCHECKOUT,
TO_CHAR(a.DATAOPERACAOCHECKOUT, 'YYYY-MM') AS ANO_MES,
a.NUMEROCHECKOUT,
a.SEQUENCIALOPERACAOCHECKOUT,
a.NUMERONOTAVENDA,
a.CODIGOBRASIF,
a.PRECOUNITARIOVENDA, a.QUANTIDADEVENDIDA,
b.INDITEMNACIONAL,
b.IDENTIFICACAOMARCA, C.DESCRICAOSUBGRUPO,
D.DESCRICAOTIPO,
b.CODIGOCATEGORIADUFRY, b.CODIGOGRUPO, b.CODIGOSUBGRUPO, b.CODIGOTIPO, b.CODIGOFORNECEDORPREFERENCIAL
FROM itvet001 a, ITEMT027 b, COMERCIAL.SGRPT001@RJD6 C, COMERCIAL.TIPOT001@RJD6 D
WHERE a.DATAOPERACAOCHECKOUT BETWEEN '01-JAN-2012' AND '01-JAN-2012'
AND A.CODIGOBRASIF=B.CODIGOBRASIF(+) AND A.CODIGONEGOCIO=B.CODIGONEGOCIO(+)
AND b.CODIGOCATEGORIADUFRY IN ('20','30')
AND B.CODIGOGRUPO=C.CODIGOGRUPO(+)
AND B.CODIGOSUBGRUPO=C.CODIGOSUBGRUPO(+)
AND B.CODIGOGRUPO=D.CODIGOGRUPO(+)
AND B.CODIGOSUBGRUPO=D.CODIGOSUBGRUPO(+)
AND B.CODIGOTIPO=D.CODIGOTIPO(+)
AND NVL(a.INDICADORESTORNO,'N')='N'
AND a.CODIGONEGOCIO='200')
GROUP BY ANO_MES, CODIGOCATEGORIADUFRY, CODIGOGRUPO, DESCRICAOSUBGRUPO, CODIGOTIPO,DESCRICAOTIPO


SELECT * FROM FL_VENDA_SUB_TIPO



