/*TRANSAÇÕES TOTAL*/
SELECT CODIGOLOJA, SIGLAAEROPORTO, TIPOLOJA, HORA, 
COUNT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT) AS TRANS,
SUM(VALORNOTAVENDABRUTO) AS VENDAS
FROM
(
SELECT VALORNOTAVENDABRUTO, NUMEROCHECKOUT, SEQUENCIALOPERACAOCHECKOUT,
TIPOLOJA,
SIGLAAEROPORTO, CODIGOLOJA, 
DATAOPERACAOCHECKOUT,
to_char(DATAHORAREALOPERACAO,'hh24') as hora, 
to_char(DATAHORAREALOPERACAO,'D') as DIA_SEM, 
to_char(DATAHORAREALOPERACAO,'hh24:mi') as hora_min, 
DATAHORAREALOPERACAO
from vndat004
WHERE CODIGONEGOCIO IN ('200') AND TIPOLOJA IN ('D','E')
AND DATAOPERACAOCHECKOUT BETWEEN '09-MAR-2010' AND '09-MAR-2010')
GROUP BY CODIGOLOJA, SIGLAAEROPORTO, TIPOLOJA, HORA


/*RESERVAS*/
SELECT LOCALPEDIDO, SIGLAAEROPORTO, HORA, 
COUNT(NUMEROPEDIDO) AS PEDIDOS,
SUM(QUANTIDADEPEDIDA*PRECOUNITARIOPEDIDO) AS VENDAS_RESERVA
FROM
(
SELECT A.NUMEROPEDIDO,
A.SIGLAAEROPORTO, A.LOCALPEDIDO, 
A.DATAPEDIDO,
to_char(A.DATAREGISTROPEDIDO,'hh24') as hora, 
to_char(A.DATAREGISTROPEDIDO,'D') as DIA_SEM, 
to_char(A.DATAREGISTROPEDIDO,'hh24:mi') as hora_min, B.QUANTIDADEPEDIDA, B.PRECOUNITARIOPEDIDO
from PEVET001 A, ITPVV001 B
WHERE A.DATAVENDA BETWEEN '08-MAR-2010' AND '08-MAR-2010'
AND A.NUMEROPEDIDO(+)=B.NUMEROPEDIDO)
GROUP BY LOCALPEDIDO, SIGLAAEROPORTO, HORA






SELECT * FROM VNDAT004
WHERE PREORDERRESGATADO>0



SELECT * FROM PEVET001
WHERE DATAPEDIDO BETWEEN '08-MAR-2010' AND '08-MAR-2010'


SELECT * FROM ITPVV001


DATAREGISTROPEDIDO
