CREATE TABLE FL_TESTE_CLI AS
SELECT DISTINCT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX 
FROM VNDAT004 A
WHERE DATAOPERACAOCHECKOUT BETWEEN '01-JAN-2014' AND '13-MAR-2015'
AND EXISTS 
(SELECT DISTINCT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX 
FROM VNDAT004 B
WHERE DATAOPERACAOCHECKOUT BETWEEN '01-SET-2015' AND '30-SET-2015'
AND B.TIPODOCUMENTOPAX = A.TIPODOCUMENTOPAX
AND B.NUMERODOCUMENTOPAX = A.NUMERODOCUMENTOPAX)


DROP TABLE FL_TESTE_CLI

CREATE TABLE FL_TESTE_CLI AS
SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, SUM(VALORNOTAVENDABRUTO) AS VENDAS,
COUNT(DISTINCT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT)) AS TICKETS
FROM VNDAT004 A WHERE DATAOPERACAOCHECKOUT BETWEEN '01-JAN-2014' AND '13-MAR-2015'
AND NVL(INDICADORESTORNO, 'N')='N'
AND EXISTS 
(SELECT DISTINCT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX 
FROM VNDAT004 B
WHERE B.DATAOPERACAOCHECKOUT BETWEEN '14-mar-2015' AND '30-apr-2015'
AND NVL(INDICADORESTORNO, 'N')='N'
AND B.TIPODOCUMENTOPAX = A.TIPODOCUMENTOPAX
AND B.NUMERODOCUMENTOPAX = A.NUMERODOCUMENTOPAX)
GROUP BY TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX




SELECT SUM(VENDAS), SUM(TICKETS) FROM (
SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, SUM(VALORNOTAVENDABRUTO) AS VENDAS,
COUNT(DISTINCT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT)) AS TICKETS
FROM VNDAT004 A WHERE DATAOPERACAOCHECKOUT BETWEEN '01-JAN-2014' AND '13-MAR-2015'
AND NVL(INDICADORESTORNO, 'N')='N' AND TIPOLOJA = 'D'
AND EXISTS 
(SELECT DISTINCT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX 
FROM VNDAT004 B
WHERE B.DATAOPERACAOCHECKOUT BETWEEN '14-mar-2015' AND '30-apr-2015'
AND NVL(INDICADORESTORNO, 'N')='N'
AND B.TIPODOCUMENTOPAX = A.TIPODOCUMENTOPAX
AND B.NUMERODOCUMENTOPAX = A.NUMERODOCUMENTOPAX)
GROUP BY TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX)





SELECT SUM(VENDAS), SUM(TICKETS) FROM (
SELECT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX, SUM(VALORNOTAVENDABRUTO) AS VENDAS,
COUNT(DISTINCT(NUMEROCHECKOUT||SEQUENCIALOPERACAOCHECKOUT)) AS TICKETS
FROM VNDAT004 A WHERE DATAOPERACAOCHECKOUT BETWEEN '14-mar-2015' AND '30-apr-2015' 
AND NVL(INDICADORESTORNO, 'N')='N' AND TIPOLOJA = 'E'
AND EXISTS 
(SELECT DISTINCT TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX 
FROM VNDAT004 B
WHERE B.DATAOPERACAOCHECKOUT BETWEEN  '01-JAN-2014' AND '13-MAR-2015'
AND NVL(INDICADORESTORNO, 'N')='N'
AND B.TIPODOCUMENTOPAX = A.TIPODOCUMENTOPAX
AND B.NUMERODOCUMENTOPAX = A.NUMERODOCUMENTOPAX)
GROUP BY TIPODOCUMENTOPAX, NUMERODOCUMENTOPAX)
